export const CART_CLASSES = {
  CART: 'shopping-cart',
  HEADER: 'shopping-cart__header',
  TITLE: 'shopping-cart__title',
  CLEAR_CART_BUTTON: 'shopping-cart__clear-button',
  LIST: 'shopping-cart__list',
  BLOCK: 'shopping-cart__block',
  BLOCK_TEXT: 'shopping-cart__block-text',
  BLOCK_BUTTON: 'shopping-cart__block-button',
  ITEM: ['shopping-cart__item', 'shopping-cart-item'],
  ITEM_IMAGE: 'shopping-cart-item__img',
  ITEM_MIDDLE_WRAPPER: 'shopping-cart-item__middle-wrapper',
  ITEM_TITLE: 'shopping-cart-item__title',
  ITEM_COUNT_WRAPPER: ['shopping-cart-item__count', 'count'],
  COUNT_MINUS_BUTTON: ['count__button', 'count__button_minus'],
  COUNT_VALUE: ['count__value'],
  COUNT_PLUS_BUTTON: ['count__button', 'count__button_plus'],
  ITEM_PRICE_WRAPPER: 'shopping-cart-item__price-wrapper',
  ITEM_PRICE: 'shopping-cart-item__price',
  ITEM_DISCOUNT_PRICE: 'shopping-cart-item__discount-price',
  ITEM_PRICE_DISABLE: 'shopping-cart-item__price_disable',
  ITEM_REMOVE_BUTTON: 'shopping-cart-item__remove-button',
  PROMO_CODE_WRAPPER: 'shopping-cart__promo-codes',
  PROMO_CODE: 'promo-code',
  PROMO_CODE_BUTTON: 'promo-code-submit',
  PRICES: 'shopping-cart__prices',
  PRICES_TOTAL: 'shopping-cart__prices-total',
  PRICES_DISCOUNT: 'shopping-cart__prices-discounted',
};

export const CART_TEXT = {
  TITLE: 'Shopping Cart',
  CLEAR_CART_BUTTON: 'Clear Cart',
  ITEM_REMOVE_BUTTON: '✖',
  COUNT_MINUS_BUTTON: ` - `,
  COUNT_PLUS_BUTTON: ` + `,
  PROMO_CODE: 'Promo code',
  PROMO_CODE_ADD_BUTTON: 'Add promo code',
  PROMO_CODE_REMOVE_BUTTON: 'Remove promo code',
};
